services:
  - type: web
    name: glow-business-board-backend
    runtime: docker
    rootDir: backend
    plan: free
    autoDeploy: true
    healthCheckPath: /management/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JHIPSTER_CORS_ALLOWED_ORIGINS
        sync: false
      - key: JHIPSTER_SECURITY_AUTHENTICATION_JWT_BASE64_SECRET
        sync: false
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
