# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

# Keep this profile focused on secret samples (JWT, etc).
# Do not override datasource here; dev/prod profiles should own database credentials.

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: YThmZTY3ODQ4Zjk1Y2QwYTZmMzZjM2Q1YmU3NGNiYTQxMmE1YWU0MjgxNjgyMGEyN2QyY2ViODRlYzFmZjg5M2Y5ZTI4MjA4YjM3ZWYwMTE2Mjk5NzI1YzBiZTFlOGQ3MDM5OTcyNzVmNTY0NDkyMzY5OGYwN2YzMGEyOTg1OGU=
